In [1]:
import pandas as pd

In [2]:
data = {
    "subject":['Purvansh','Pavan','Poojith','Kaushali','Hridhan','Parinith'],
    'maths':['88','80','78','96','100','90'],
    'Physics':['94','90','96','88','80','90'],
    'P.E':['92','92','34','70','96','84'],
    'English':['88','70','72','98','68','78'],
    'C.S':['78','76','70','90','80','81'],
    'History':['88','90','88','84','86','88']
}
df = pd.DataFrame(data,index=[1,2,3,4,5,6])
df

    subject maths Physics P.E English C.S History
1  Purvansh    88      94  92      88  78      88
2     Pavan    80      90  92      70  76      90
3   Poojith    78      96  34      72  70      88
4  Kaushali    96      88  70      98  90      84
5   Hridhan   100      80  96      68  80      86
6  Parinith    90      90  84      78  81      88

In [3]:
df.to_csv('Students.csv',index = False)

In [4]:
city = ['Madikeri','Madikeri','Mysore',"Bangalore",'Madikeri','Mysore']
df['city'] = city

In [5]:
df

    subject maths Physics P.E English C.S History       city
1  Purvansh    88      94  92      88  78      88   Madikeri
2     Pavan    80      90  92      70  76      90   Madikeri
3   Poojith    78      96  34      72  70      88     Mysore
4  Kaushali    96      88  70      98  90      84  Bangalore
5   Hridhan   100      80  96      68  80      86   Madikeri
6  Parinith    90      90  84      78  81      88     Mysore

In [6]:

city_pos = df.columns.get_loc('city')
print(city_pos)

7

In [7]:

subject = ['maths','Physics','P.E','English','C.S','History']

df[subject] = df[subject].apply(pd.to_numeric)

Total = df[subject].sum(axis = 1)
df.insert(city_pos ,"Total" ,Total)
df

    subject  maths  Physics  P.E  English  C.S  History  Total       city
1  Purvansh     88       94   92       88   78       88    528   Madikeri
2     Pavan     80       90   92       70   76       90    498   Madikeri
3   Poojith     78       96   34       72   70       88    438     Mysore
4  Kaushali     96       88   70       98   90       84    526  Bangalore
5   Hridhan    100       80   96       68   80       86    510   Madikeri
6  Parinith     90       90   84       78   81       88    511     Mysore

In [8]:
Percent = df['Total'] / len(subject)
df.insert(city_pos, "Percentage", Percent)
df

,subject,maths,Physics,P.E,English,C.S,History,Percentage,Total,city
1,Purvansh,88,94,92,88,78,88,88.000000,528,Madikeri
2,Pavan,80,90,92,70,76,90,83.000000,498,Madikeri
3,Poojith,78,96,34,72,70,88,73.000000,438,Mysore
4,Kaushali,96,88,70,98,90,84,87.666667,526,Bangalore
5,Hridhan,100,80,96,68,80,86,85.000000,510,Madikeri
6,Parinith,90,90,84,78,81,88,85.166667,511,Mysore

In [9]:
cols = list(df.columns)
t = cols.index("Total")
p = cols.index("Percentage")
cols[p],cols[t] = cols[t],cols[p]
df = df[cols]
df

,subject,maths,Physics,P.E,English,C.S,History,Total,Percentage,city
1,Purvansh,88,94,92,88,78,88,528,88.000000,Madikeri
2,Pavan,80,90,92,70,76,90,498,83.000000,Madikeri
3,Poojith,78,96,34,72,70,88,438,73.000000,Mysore
4,Kaushali,96,88,70,98,90,84,526,87.666667,Bangalore
5,Hridhan,100,80,96,68,80,86,510,85.000000,Madikeri
6,Parinith,90,90,84,78,81,88,511,85.166667,Mysore

In [10]:
def get_grade(p):

 if(p >= 90 ):
   return  'A'
 elif(p >= 85):
   return 'B'
 elif(p >=75 ):
   return 'C'
 else:
    return 'D'

df['Grade'] = df['Percentage'].apply(get_grade)
df

,subject,maths,Physics,P.E,English,C.S,History,Total,Percentage,city,Grade
1,Purvansh,88,94,92,88,78,88,528,88.000000,Madikeri,B
2,Pavan,80,90,92,70,76,90,498,83.000000,Madikeri,C
3,Poojith,78,96,34,72,70,88,438,73.000000,Mysore,D
4,Kaushali,96,88,70,98,90,84,526,87.666667,Bangalore,B
5,Hridhan,100,80,96,68,80,86,510,85.000000,Madikeri,B
6,Parinith,90,90,84,78,81,88,511,85.166667,Mysore,B

In [11]:
def pass_fail(row):
    if all(row[s] >= 40 for s in subject):
        return 'PASS'
    else:
        return 'FAIL'

df['Result'] = df.apply(pass_fail,axis = 1)
df

,subject,maths,Physics,P.E,English,C.S,History,Total,Percentage,city,Grade,Result
1,Purvansh,88,94,92,88,78,88,528,88.000000,Madikeri,B,PASS
2,Pavan,80,90,92,70,76,90,498,83.000000,Madikeri,C,PASS
3,Poojith,78,96,34,72,70,88,438,73.000000,Mysore,D,FAIL
4,Kaushali,96,88,70,98,90,84,526,87.666667,Bangalore,B,PASS
5,Hridhan,100,80,96,68,80,86,510,85.000000,Madikeri,B,PASS
6,Parinith,90,90,84,78,81,88,511,85.166667,Mysore,B,PASS

In [16]:
df['Rank'] = df['Percentage'].rank(ascending = False).astype(int)
df

,subject,maths,Physics,P.E,English,C.S,History,Total,Percentage,city,Grade,Result,Rank
1,Purvansh,88,94,92,88,78,88,528,88.000000,Madikeri,B,PASS,1
2,Pavan,80,90,92,70,76,90,498,83.000000,Madikeri,C,PASS,5
3,Poojith,78,96,34,72,70,88,438,73.000000,Mysore,D,FAIL,6
4,Kaushali,96,88,70,98,90,84,526,87.666667,Bangalore,B,PASS,2
5,Hridhan,100,80,96,68,80,86,510,85.000000,Madikeri,B,PASS,4
6,Parinith,90,90,84,78,81,88,511,85.166667,Mysore,B,PASS,3

In [17]:
df.to_csv('Results.csv')